### ISSUE TITLE
[BUG] `hex` method discards alpha

### ISSUE THREAD

**Issue by devkvlt** [Qix-/color#238] opened 2021-12-20 11:43 UTC
Fix: `npm uninstall color`

**Comment by Qix-** [comment] 2021-12-20 20:18
This isn't a bug, it's just part of how the library works. Please search the issues next time.

Duplicate of #72.

**Closed by Qix-** 2021-12-20 20:18 UTC

**Comment by devkvlt** [comment] 2021-12-20 21:48
> Please search the issues next time.

Boldly implying I didn't.. 

> This isn't a bug

Discarding user information without even throwing an exception is a massive bug.. It's okay if you don't want to add something like `hexa` and `ahex` in your lib, but at least do us the courtesy of throwing an error when we use `hex` method on a color that has alpha.

**Comment by Qix-** [comment] 2021-12-21 00:51
No thanks, and the tone isn't appreciated.
