### ISSUE TITLE
Lightness manipulation methods fail on color('black'), except negate()

### ISSUE THREAD

**Issue by xml** [Qix-/color#82] opened 2016-03-28 03:20 UTC
Hi, color team. This lib is great, and seems to work normally... except on any version of the color black. 

On black, if I try to lighten it, nothing changes. `lighten(0.5)` and `whiten(0.5)` fail completely on black, where they work fine on other colors, or on grey. And `darken()` works fine on white. It's just black that fails. (And I'm baffled by the results of `lightness(0.5)`, but that might be more a question of my understanding. :-)

`negate()` works, and converts it to white. `alpha(0.5)` works.

`mix()` also seems to work on black.

I've tried hard to test this thoroughly. You can see a series of experiments on this Tonic, and you can manipulate the 'source' color to see the varying results: https://tonicdev.com/xmlilley/testing-color-lib

Please let me know if I'm somehow just misunderstanding either color-theory or the API. It's certainly possible. If nothing else, this behavior is at least violating the principle-of-least-surprise for me. :-)

Is this project active, and are you taking PR's for the current branch, or only for your 1.0 milestone?

**Comment by Qix-** [comment] 2016-03-28 03:29
We're certainly active :)

The 1.0 milestone is a rewrite of the underlying code (meaning the API should be 1:1), though I'm more than happy to see bugs get squashed so I can make sure to have those tests in the new version.

Could you PR a failing test? I'd really appreciate it.

---

On a side note, `whiten()` and `lighten()` do ambiguous things, admittedly. I'll have to go in and see the intended functionality, but this does sound like a bug nonetheless.

**Comment by xml** [comment] 2016-03-28 08:39
Note: `color('white').blacken()` also fails. Working on some tests now.

**Comment by Qix-** [comment] 2016-03-28 18:22
Ah. I see what's going on.

This will get fixed with the rewrite. This was a regression introduced from #56.

**Comment by xml** [comment] 2016-04-03 13:56
This wasn't actually a bug. This was simply a misunderstanding about the difference between the relative and absolute setters, and how similarly-named methods don't work the way SASS/LESS does. 

So, I've created a PR for documentation instead: https://github.com/Qix-/color/pull/85

**Comment by mrbinky3000** [comment] 2016-05-13 16:11
Just to be clear, will lighten work on black in the future or is this a documentation problem?  If it is a documentation problem, which method should we use when we want to lighten #000000 by 50% to get #767676

**Comment by diegohaz** [comment] 2016-06-22 20:44
This is the first thing I tried to do with `color` and it failed :(

**Comment by fab1an** [comment] 2016-08-19 09:13
Same here:

`Color("white").darken(0.8).hslString() !== Color("black").lighten(0.2)`

**Comment by Qix-** [comment] 2016-11-16 05:33
Hi @fab1an - that's the color model's fault, not Color's. In this case, Color is behaving correctly. Those methods use HWB. That color model is notoriously tricky, and I've considered not using it a few times now other than basic support.

I have this marked under the makeover track (which I'm preparing as we speak). I would love to hear new ideas for what kinds of functionality you'd like to see in terms of tinting/shading since there are lots of different kinds of operations that could take place.

**Closed** 2016-12-03 12:15 UTC
Labels: bug
