### ISSUE TITLE
hex with rgba

### ISSUE THREAD

**Issue by DrDr3ck** [Qix-/color#188] opened 2020-12-02 10:35 UTC
Hi,

if I got a rgb color on which I add an alpha, the hex function will only return the rgb transformation and not the rgba transformation. Is it expected ? Should we have a hexa() function that will return the rgba transformation ?

example:
const color = Color("#72FFFF");
color.alpha(0.5);
console.log(color.hex());

=> #72FFFF

**Comment by Qix-** [comment] 2020-12-02 10:37
Please search the issues before opening a new issue.

Duplicate of #125.

**Closed by Qix-** 2020-12-02 10:37 UTC
