### ISSUE TITLE
Some lines are breaking Android and Web Browser builds

### ISSUE THREAD

**Issue by fsmalaquias** [Qix-/color#207] opened 2021-07-28 18:17 UTC
I've posted details here

https://stackoverflow.com/questions/68548389/after-installing-magnus-ui-in-expo-app-getting-error-no-space-between-hexadecim/68563541#68563541

Changing 2 lines of code solved my problem

**Comment by Qix-** [comment] 2021-07-28 19:16
Please search next time. Duplicate of #206.

**Closed by Qix-** 2021-07-28 19:16 UTC
