### ISSUE TITLE
issue with storybook/webpack and number format like 0xFF_FF_FF;

### ISSUE THREAD

**Issue by pmnc-philippe** [Qix-/color#209] opened 2021-08-02 14:13 UTC
Hello -
I am using the latest of your great lib with storybook latest and having trouble with lines:
line 66: 		object &= 0xFF_FF_FF;
line 258:          lum[i] = (chan <= 0.039_28) ? chan / 12.92 : ((chan + 0.055) / 1.055) ** 2.4;

_Module parse failed: Identifier directly after number (258:26)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 		for (const [i, element] of rgb.entries()) {
| 			const chan = element / 255;
> 			lum[i] = (chan <= 0.039_28) ? chan / 12.92 : ((chan + 0.055) / 1.055) ** 2.4;
| 		}_

Would it be possible to correct these two lines as follow:

**line 66: 		object &= 0xFFFFFF;
line 258:          lum[i] = (chan <= 0.03928) ? chan / 12.92 : ((chan + 0.055) / 1.055) ** 2.4;**

Thank you very much in advance

**Comment by Qix-** [comment] 2021-08-02 15:36
Please search next time. Duplicate of #204.

**Closed by Qix-** 2021-08-02 15:36 UTC
